# Arrays, Matrices & Tensores

Arrays es el objeto mas potente y útil en Julia. Exploremos algunos fundamentos.

In [1]:
students = ["jack", "jill", "john"]

3-element Vector{String}:
 "jack"
 "jill"
 "john"

In [2]:
typeof(students)

Vector{String} (alias for Array{String, 1})

'String' define el tipo de elementos en el Array y '1' indica la dimensión del Array. Por tanto, este array es unidimensional de valores string.

In [3]:
fib = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [4]:
typeof(fib)

Vector{Int64} (alias for Array{Int64, 1})

In [5]:
push!(fib, 21)

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

In [6]:
@show fib; 

fib = [1, 1, 2, 3, 5, 8, 13, 21]


In [7]:
pop!(fib) # eliminar un valor del array

21

In [8]:
@show fib;

fib = [1, 1, 2, 3, 5, 8, 13]


## 2D Arrays

In [9]:
mat = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9, 24]
]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9, 24]

In [10]:
typeof(mat)

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

**Importante** un array 2D **no** es una matriz. Es un array 1D pero cada elemento es un array unidimensional!

Vamos a crear arrays bi-dimensionales

## Matrices 

In [11]:
x = [1 2 3]       # observa que no necesitamos ',' entre los elementos ni las dimensiones

1×3 Matrix{Int64}:
 1  2  3

In [12]:
x'                # lo transpone o lo convierte a un vector

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [13]:
mat = [
       [1  2  3] 
       [4  5  6] 
       [7  8  9]
      ]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [14]:
typeof(mat)

Matrix{Int64} (alias for Array{Int64, 2})

### Tamaños (Shapes) y Re-fomateo

In [15]:
size(mat)     # muy importante en machine learning 

(3, 3)

In [16]:
size(x)

(1, 3)

In [17]:
size(fib)     # diferencia importante 

(7,)

In [18]:
X = [
       [1   2   3] 
       [4   5   6] 
       [7   8   9]
       [10  11  12]
      ]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [19]:
X = reshape(X, 2, 6)

2×6 Matrix{Int64}:
 1   7  2   8  3   9
 4  10  5  11  6  12

In [20]:
X = reshape(X, 12, 1)

12×1 Matrix{Int64}:
  1
  4
  7
 10
  2
  5
  8
 11
  3
  6
  9
 12

In [21]:
X = reshape(X, 4, 3)

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

## Functiones útiles 

### Creando Matrices Random

In [22]:
rand(4, 3)

4×3 Matrix{Float64}:
 0.742342  0.814506  0.195766
 0.282074  0.918096  0.214641
 0.130744  0.085191  0.0838521
 0.817308  0.592883  0.0216256

In [23]:
mat = rand(4, 3)

4×3 Matrix{Float64}:
 0.962364  0.0355578  0.31972
 0.11829   0.38804    0.531702
 0.916149  0.604894   0.133634
 0.465471  0.151603   0.83443

In [24]:
mat_2 = mat;

In [25]:
mat_2[1, 1] = 100.0 # asignando valores

100.0

In [26]:
mat_2

4×3 Matrix{Float64}:
 100.0       0.0355578  0.31972
   0.11829   0.38804    0.531702
   0.916149  0.604894   0.133634
   0.465471  0.151603   0.83443

In [27]:
mat # es mutable tambien

4×3 Matrix{Float64}:
 100.0       0.0355578  0.31972
   0.11829   0.38804    0.531702
   0.916149  0.604894   0.133634
   0.465471  0.151603   0.83443

### Copiando Arrays 

In [28]:
mat_3 = copy(mat)  
# crea una copia de los valores, pero los arrays / matrices son inmutables entre si

4×3 Matrix{Float64}:
 100.0       0.0355578  0.31972
   0.11829   0.38804    0.531702
   0.916149  0.604894   0.133634
   0.465471  0.151603   0.83443

In [29]:
mat_3[1, 1] = 999.0

999.0

In [30]:
mat

4×3 Matrix{Float64}:
 100.0       0.0355578  0.31972
   0.11829   0.38804    0.531702
   0.916149  0.604894   0.133634
   0.465471  0.151603   0.83443

In [31]:
mat_3

4×3 Matrix{Float64}:
 999.0       0.0355578  0.31972
   0.11829   0.38804    0.531702
   0.916149  0.604894   0.133634
   0.465471  0.151603   0.83443

## Comprehensions 

Es posible hacer 'nested loops' con 'comprehensions'

In [32]:
[i^2 for i in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [33]:
[(i, j) for i in 1:5, j in 6:10]      # producto cartesiano (nested loop)

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 6)  (1, 7)  (1, 8)  (1, 9)  (1, 10)
 (2, 6)  (2, 7)  (2, 8)  (2, 9)  (2, 10)
 (3, 6)  (3, 7)  (3, 8)  (3, 9)  (3, 10)
 (4, 6)  (4, 7)  (4, 8)  (4, 9)  (4, 10)
 (5, 6)  (5, 7)  (5, 8)  (5, 9)  (5, 10)

In [34]:
[(i^2, j+1//2) for i in 1:5, j in 6:10]

5×5 Matrix{Tuple{Int64, Rational{Int64}}}:
 (1, 13//2)   (1, 15//2)   (1, 17//2)   (1, 19//2)   (1, 21//2)
 (4, 13//2)   (4, 15//2)   (4, 17//2)   (4, 19//2)   (4, 21//2)
 (9, 13//2)   (9, 15//2)   (9, 17//2)   (9, 19//2)   (9, 21//2)
 (16, 13//2)  (16, 15//2)  (16, 17//2)  (16, 19//2)  (16, 21//2)
 (25, 13//2)  (25, 15//2)  (25, 17//2)  (25, 19//2)  (25, 21//2)

## Operaciones con Matrices 

In [35]:
A = rand(10:20, 3, 3)
# Matriz 3x3 con cada elmento entre 10 y 20 

3×3 Matrix{Int64}:
 14  13  16
 17  13  20
 18  11  11

In [43]:
A = rand(10.:20, 3, 3) 
# Cambiando el rango, cambia el tipo a Float64

3×3 Matrix{Float64}:
 11.0  16.0  19.0
 19.0  14.0  10.0
 11.0  10.0  11.0

En vez de usar valores aleatorios, podemos asignar valores especificos con **fill**

In [37]:
x = fill(10.0, (3, ))

3-element Vector{Float64}:
 10.0
 10.0
 10.0

In [38]:
A*x 
# esta es la operacion de multiplicar un vector por una matriz (requiere un ajuste de 'size match') 

3-element Vector{Float64}:
 400.0
 430.0
 490.0

### Transpose, Trace, Determinant

In [39]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 12.0  12.0  14.0
 10.0  18.0  15.0
 18.0  13.0  20.0

In [46]:
A' * A

3×3 Matrix{Float64}:
 603.0  552.0  520.0
 552.0  552.0  554.0
 520.0  554.0  582.0

In [44]:
A'A      # shortcut ... tipico de Julia 

3×3 Matrix{Float64}:
 603.0  552.0  520.0
 552.0  552.0  554.0
 520.0  554.0  582.0

In [47]:
tr(A)     # trace de A 

LoadError: UndefVarError: tr not defined

In [48]:
using LinearAlgebra # invocar un paquete instalado

In [49]:
det(A)    # determinant necesita el paquete LinearAlgebra 

-305.9999999999999

In [50]:
inv(A)

3×3 Matrix{Float64}:
 -0.176471  -0.0457516   0.346405
  0.323529   0.287582   -0.820261
 -0.117647  -0.215686    0.490196

## Resolver ecuaciones Lineales directamente 

In [51]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.718613  0.69048   0.671767
 0.913804  0.348843  0.822377
 0.801306  0.42128   0.671731

In [52]:
x

3-element Vector{Float64}:
 10.0
 10.0
 10.0

In [53]:
b = A*x

3-element Vector{Float64}:
 20.808600632865016
 20.850239373222987
 18.943173003748832

In [54]:
A\b  # Solve for b 

3-element Vector{Float64}:
  9.999999999999986
 10.000000000000004
 10.000000000000012

## Mas ... 

Se pueden crear n-dim arrays facilmente. Estos tensores son muy útiles en machine learning.

In [55]:
rand(4, 3, 2, 5)

4×3×2×5 Array{Float64, 4}:
[:, :, 1, 1] =
 0.404759  0.765286  0.102529
 0.30605   0.201866  0.218889
 0.698634  0.913608  0.641137
 0.536745  0.804473  0.455469

[:, :, 2, 1] =
 0.488777   0.628932   0.137866
 0.75414    0.784747   0.643433
 0.0970311  0.755797   0.32278
 0.318185   0.0328117  0.839912

[:, :, 1, 2] =
 0.691901  0.447272  0.975492
 0.289906  0.670797  0.928073
 0.53104   0.50987   0.503928
 0.144459  0.123768  0.227668

[:, :, 2, 2] =
 0.590969  0.95383     0.708265
 0.784044  0.377008    0.463388
 0.371066  0.00432103  0.403252
 0.623865  0.913963    0.929829

[:, :, 1, 3] =
 0.317553  0.33722   0.0571102
 0.578479  0.557459  0.242973
 0.601016  0.770839  0.676911
 0.700125  0.938048  0.56107

[:, :, 2, 3] =
 0.487944   0.69636    0.441643
 0.314279   0.759119   0.666434
 0.0655472  0.0219641  0.524517
 0.157179   0.0570409  0.681961

[:, :, 1, 4] =
 0.437032  0.681014  0.396224
 0.390044  0.216322  0.962701
 0.168688  0.735583  0.291727
 0.705645  0.166846  0.625425

Explore el paquete LinearAlgebra para más operaciones. https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/