# Programacion Funcional Elemental 

La Programacion Funcional es muy útil en términos de pensamiento matemático. Es altamente paralelizable y se deberían entender los conceptos básicos, que veremos a continuación.

## Map 

Map aplica una funcion a todos los elementos de una colección

In [1]:
collection = [1, 2, 4]

3-element Vector{Int64}:
 1
 2
 4

In [2]:
map(x -> x^2, collection) # aplicando 'map()'

3-element Vector{Int64}:
  1
  4
 16

In [3]:
squares = map(x -> x^2, collection);

In [4]:
@show squares;

squares = [1, 4, 16]


`map` es por tanto una **función de orden superior** en tanto que toma argumentos en si misma. La programación funcional se desarrolla sobre este concepto.
Es muy util dado que se puede paralelizar, aumentando su rendimiento y velocidad en cálculos muy grandes. Hay algoritmos que resuelven casos muy comunes en programación funcional, tales como `map`, `reduce` y `filter`

## Reduce 


In [5]:
collection = [1, 2, 4, 10]

4-element Vector{Int64}:
  1
  2
  4
 10

In [6]:
reduce(+, collection)  # aplica la función 'reduce()' a los dos primeros elementos, luego agrega el tercero, y así sucesivamente...  

17

## Broadcast 

In [7]:
collection = [1, 2, 4]

3-element Vector{Int64}:
 1
 2
 4

In [8]:
function f(x) 
    x ^ 2 
end

f (generic function with 1 method)

In [9]:
broadcast(f, collection)      # parece similar a 'map()'

3-element Vector{Int64}:
  1
  4
 16

In [10]:
collection

3-element Vector{Int64}:
 1
 2
 4

In [11]:
f.(collection)   # lo interesante es que dispone de un atajo 

3-element Vector{Int64}:
  1
  4
 16

In [12]:
f(collection)     # no funciona poarque no se puede hacer el cuadrado de un array 

LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(::LinearAlgebra.Diagonal, ::Integer) at C:\julia184\Julia-1.8.4\share\julia\stdlib\v1.8\LinearAlgebra\src\diagonal.jl:208
  ^(::LinearAlgebra.Diagonal, ::Real) at C:\julia184\Julia-1.8.4\share\julia\stdlib\v1.8\LinearAlgebra\src\diagonal.jl:207
  ...

Veamos como `broadcast` es diferente a una invocacion normal

In [13]:
m = ones(3, 3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [14]:
f(m)      # esto es m^2, que es igual a m*m 

3×3 Matrix{Float64}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [15]:
f.(m)     # esto aplica x^2 a cada elemento por separado 

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [16]:
A = [
     [1 2 3]
     [4 5 6]
     [7 8 9]
    ]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [17]:
A .+ 1     # aplica +1 a cada elemento por separado 

3×3 Matrix{Int64}:
 2  3   4
 5  6   7
 8  9  10

In [18]:
A .* 2 

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18

In [19]:
# o incluso... 
2A   

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18

In [20]:
f.(2A) # se puede escribir funciones muy similares a como se hace en matemáticas

3×3 Matrix{Int64}:
   4   16   36
  64  100  144
 196  256  324

### Broadcast para Matrices 

In [21]:
A = [
    [1 2 3]
    [4 5 6]
    ]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [22]:
# sin broadcasting 
A * [10 20 30]             # funciona si se transpone, pero es una operación diferente

LoadError: DimensionMismatch: matrix A has dimensions (2,3), matrix B has dimensions (1,3)

In [23]:
A = [
    [1  2  3]
    [4  5  6]
    ];

In [24]:
# con broadcasting 

A .* [10 20 30]          # vector linea se duplica por cada línea 

2×3 Matrix{Int64}:
 10   40   90
 40  100  180

In [25]:
A .* [10 20]'            # vector columna se duplica por cada columna

2×3 Matrix{Int64}:
 10   20   30
 80  100  120