# Interactuando con otros lenguajes de programación 

## Llamadas a Python Builtins y Custom Code

Es necesario instalar los paquetes necesarios para abrir interfaz con Python. Usamos el comando **package mode** 

In [1]:
] add PyCall # una vez instalado el paquete no es necesario volver a instalarlo. Para actualizarlo usar '] update xxxx'

    Updating registry at `C:\Users\pmore\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\pmore\.julia\environments\v1.8\Project.toml`
  [438e738f] + PyCall v1.94.1
  No Changes to `C:\Users\pmore\.julia\environments\v1.8\Manifest.toml`


In [2]:
using PyCall

In [3]:
math = pyimport("math")
math.sin(math.pi / 4)

0.7071067811865476

In [4]:
math.sqrt(36)

6.0

In [5]:
push!(pyimport("sys")["path"], pwd()); 

In [6]:
pyex = pyimport("pyex")

PyObject <module 'pyex' from 'C:\\Users\\pmore\\OneDrive\\Documents\\Julia\\all-resources\\notebooks\\pyex.py'>

In [7]:
pyex.sqrt(36)

"The square root of ... : 36 is 6.0"

In [8]:
pyimport("importlib")."reload"(pyex) # si se cambia algo en el modulo de python, hay que volver a cargarlo

PyObject <module 'pyex' from 'C:\\Users\\pmore\\OneDrive\\Documents\\Julia\\all-resources\\notebooks\\pyex.py'>

In [9]:
pyex.sqrt(36)

"The square root of ... : 36 is 6.0"

## Interfaz con R

In [10]:
] add RCall

   Resolving package versions...
   Installed StatsFuns ─────────────── v1.1.1
   Installed WinReg ────────────────── v0.3.1
   Installed DualNumbers ───────────── v0.6.8
   Installed Rmath_jll ─────────────── v0.3.0+0
   Installed Calculus ──────────────── v0.5.1
   Installed HypergeometricFunctions ─ v0.3.11
   Installed StatsModels ───────────── v0.6.33
   Installed Rmath ─────────────────── v0.7.0
   Installed RCall ─────────────────── v0.13.14
   Installed ShiftedArrays ─────────── v2.0.0
    Updating `C:\Users\pmore\.julia\environments\v1.8\Project.toml`
  [6f49c342] + RCall v0.13.14
    Updating `C:\Users\pmore\.julia\environments\v1.8\Manifest.toml`
  [49dc2e85] + Calculus v0.5.1
  [fa6b7ba4] + DualNumbers v0.6.8
  [34004b35] + HypergeometricFunctions v0.3.11
  [6f49c342] + RCall v0.13.14
  [79098fc4] + Rmath v0.7.0
  [1277b4bf] + ShiftedArrays v2.0.0
  [4c63d2b9] + StatsFuns v1.1.1
  [3eaba693] + StatsModels v0.6.33
  [1b915085] + WinReg v0.3.1
  [f50d1b31] + Rmath_jll v0.3.0+

In [11]:
using RCall

In [12]:
X = randn(3,2)
b = reshape([2.0, 3.0], 2,1)
y = X * b + randn(3,1)

3×1 Matrix{Float64}:
 -0.14527400089842324
 -1.029940889615414
 -0.17281619476669244

In [13]:
X

3×2 Matrix{Float64}:
  0.396491    0.633015
  0.0950858  -0.743811
 -0.342056    0.137701

In [14]:
b

2×1 Matrix{Float64}:
 2.0
 3.0

In [15]:
y

3×1 Matrix{Float64}:
 -0.14527400089842324
 -1.029940889615414
 -0.17281619476669244

In [16]:
@rput y
@rput X

3×2 Matrix{Float64}:
  0.396491    0.633015
  0.0950858  -0.743811
 -0.342056    0.137701

In [17]:
R"z <- y * 3"   

RObject{RealSxp}
           [,1]
[1,] -0.4358220
[2,] -3.0898227
[3,] -0.5184486


In [18]:
@rget z
@show z     

z = [-0.4358220026952697; -3.0898226688462422; -0.5184485843000773;;]


3×1 Matrix{Float64}:
 -0.4358220026952697
 -3.0898226688462422
 -0.5184485843000773